### PR TITLE
Mkdocs Material for documentation

### PR DESCRIPTION
**Pull request by ijmitch**
This fork has taken the contents of the README and the wiki to form the basis for a Github Pages site using [Mkdocs Material](squidfunk.github.io/mkdocs-material/). I've used the standard form of Github Actions to automate the build and deploy to a `gh-pages` branch.

The fork's deployment can be seen at https://ijmitch.github.io/tnz/ .

### CODE REVIEW

**Comment by ijmitch** [comment]
The settings to activate Github Pages:

- Deploy from branch
  - `/root` of `gh-pages` branch

image

**Comment by ijmitch** [comment]
I just remembered that moving the images would break the links in the actual README.md.

I also realise that I don't know what the Github Pages URL will turn out to be... hope I've not been forgetting something crucial about how it would work for a repo in the `/IBM` org!

**Comment by najohnsn** [comment]
Thanks for contributing!

At least in one test of looking at your fork, the url changes to the images didn't cause any problems. 

I believe the url will be http://pages.github.com/IBM/tnz. I'll prime a gh-pages branch with yours and enable it so we can verify that. 

The .md files are generated, right? Can they be removed from the commit? I expect GitHub actions will generate them and push them to gh-pages - so not needed in main branch.

**Comment by najohnsn** [comment]
Oh... now I see. The new .md files are _copies_ from the wiki. 🤫

**Comment by najohnsn** [comment]
Could the girhub actions script clone the wiki into the docs folder instead of putting a copy in the main branch? Or do the .md files need to be _hand-modified_ in some way?

**Comment by ijmitch** [comment]
Well, I guess I was expecting that the doc would now go entirely in the `docs` folder. What's the advantage of the wiki vs some Markdown in `docs`?

**Comment by najohnsn** [comment]
> What's the advantage of the wiki vs some Markdown in `docs`?

I guess I would first ask what the advantage is of gh-pages serving markdown over a "built-in" GitHub wiki.

I can see that the ability to do PRs on doc would be an advantage in storing the markdown in a `docs` directory.

But if it was decided that a `docs` directory is better than a separate branch or wiki repo, then it still begs the question of the use of mkdocs+gh-pages verses wiki - I believe GitHub actions could easily direct content to either.

I think that the downside of mkdocs+gh-pages is that it _requires_ automation (GitHub actions). And it introduces another 3rd party tool (mkdocs) instead of using the built-in GitHub support.

The one advantage of gh-pages that I can think of is that I would eventually like to automatically extract doc from the python docstrings and _publish_ it somewhere. If the output to _publish_ would be markdown, then wiki would be fine. But I haven't seen any tool that been able to produce markdown with reasonable formatting from python docstrings. But I _have_ seen tools produce doc in html - suitable for gh-pages.  Though I don't know if mkdocs can do this and this isn't part of this PR.

**Comment by ijmitch** [comment]
You're right, there are lots of mkdocs plugins and I just happen to be happy with Material for various other projects.

I actually do have a branch on my fork which is already using https://mkdocstrings.github.io/python/ ...
image

**Comment by ijmitch** [comment]
As for 'built-in' vs mkdocs... gh-pages defaults to [Jekyll](https://jekyllrb.com/) but unless you are happy with the few themes which Github offer then you need to pick another one - which is actually dead easy with a line in the `_config.yml` (see [remote-themes](https://github.com/benbalter/jekyll-remote-theme)).

**Comment by najohnsn** [comment]
Been thinking a lot about this PR. I think that this is much better than a wiki. I will merge this and I expect to eventually deprecate the wiki.

**Pull request merged**
